esp_toml_version = 1.0

# This should be a publicly accessible URL of the file server where your firmware binaries are available for download
firmware_images_url = "<https://github.com/lisir233/esp_smart_light_controller/tree/master/bin>"

# Apps that you support and for which the binaries are available to publish. You can have multiple apps as a comma separated list
# The launch pad UI will automatically show these Apps in the available apps dropdown
# There should be a config section per listed App
supported_apps = ["ESP32C3_SMART_LIGHT_CONTROLLER"]


[YOUR_FIRMWARE_APP_NAME]
# ESP32 Chipsets for which you have a supported Firmware App. Define a property for each supported chipset in the given format.
chipsets = ["ESP32-C3"]
# Configure the name of the binary file
image.esp32-c3 = "esp32c3_switch_v1_0.bin"
# Optional: Phone APP URLs if any for Playstores
android_app_url = ""
ios_app_url = ""